baseurl = "http://humboldtux.github.io/sbcb-demo"
themeDir = "themes"
publishDir ="docs"
title = "DevMecha Blog"
canonifyurls = true
paginate = 10
theme = "sbootstrap"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."
googleAnalytics = "" # delete or comment to disable Google Analytics JS generation
disqusShortname = "YourDisqusShortname" #delete or comment to disable Disqus comments

[author]
  name = "DevMecha"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "My Classic Blog With Hugo"
  Author = "DevMecha"
  email = "mechadev.contact@gmail.com" #Remove this line if you would prefer not to use an email button in the footer.
  postSummariesFrontPage = 4 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = true #set to false to exclude read time from header of post

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/DevMecha"
[[params.social]]
  title = "github"
  url = "https://github.com/devmecha"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
